language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
  - "pypy3"
# command to install dependencies
install:
  - pip install -e '.[test]'
# command to run tests
script:
  - pytest --cov=.
